### ISSUE TITLE
ruby syntax errors and attributes

### ISSUE THREAD

**Issue by harsimranrajpal21** [inspec/kitchen-inspec#191]
trying to run below code and getting an error:

```
testabc$ cat test08.rb
# encoding: utf-8
#
OR_DBA = attribute(
  'or_dba',
  description: 'The oracle DBA user to access the test database',
  default: 'ora_dba'
)

OR_DBA_PASSWORD = attribute(
  'or_dba_password',
  description: 'The password for the oracle DBA user',
  default: 'ora_dba_password'
)

OR_DB = attribute(
 'or_db',
 description: 'The database used for tests',
 default: 'database'
)

OR_HOST = attribute(
 'or_host',
 description: 'The hostname or IP address used to connect to the database',
 default: '127.0.0.1'
)

OR_PORT = attribute(
 'or_port',
 description: 'The port used to connect to the database',
 default: '4567'
)

control 'OR-2810' do
 title 'DB connectivity test.'
 desc  'In order to prevent unauthorized connection of devices, unauthorized
       transfer of information, or unauthorized tunneling'
 impact 0.1
 sql = oracledb_session(user: #{OR_DB}, service: #{OR_DBA}, password: #{OR_DBA_PASSWORD}, host: #{OR_HOST}, port: #{OR_PORT})
 describe sql.query(%("""SELECT UPPER(VALUE) AS VALUE FROM V$PARAMETER WHERE UPPER(NAME)='AUDIT_TRAIL';""")).row(0).column('value') do
   its('value') { should eq 'DB, EXTENDED' }
 end
end
```

```
inspec exec test08.rb
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/profile_context.rb:158:in `instance_eval': test08.rb:39: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '(' (SyntaxError)
 describe sql.query(%("""SELECT UPPER(VALUE
             ^
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/profile_context.rb:158:in `load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/profile_context.rb:142:in `load_control_file'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/profile.rb:170:in `block in collect_tests'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/profile.rb:167:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/profile.rb:167:in `collect_tests'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/runner.rb:93:in `block in load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/runner.rb:82:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/runner.rb:82:in `load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/runner.rb:103:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/cli.rb:168:in `exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/bin/inspec:12:in `<top (required)>'
        from /bin/inspec:137:in `load'
        from /bin/inspec:137:in `<main>'
```

EDIT: (@clintoncwolfe) - place code in code blocks

**Comment by clintoncwolfe** [comment]
You have several Ruby syntax errors throughout these lines:
```
sql = oracledb_session(user: #{OR_DB}, service: #{OR_DBA}, password: #{OR_DBA_PASSWORD}, host: #{OR_HOST}, port: #{OR_PORT})
 describe sql.query(%("""SELECT UPPER(VALUE) AS VALUE FROM V$PARAMETER WHERE UPPER(NAME)='AUDIT_TRAIL';""")).row(0).column('value') do
   its('value') { should eq 'DB, EXTENDED' }
 end
```

They are all related to how string values are quoted.  `#{OR_DB}` is a syntax error if used alone; that structure is used to interpolate in a double quoted string (like this: `"#{OR_DB}"`).  But you don't need to do that; OR_BD is already an expression, you can just use it as-is:

```
sql = oracledb_session(user: OR_DB, service: OR_DBA, password: OR_DBA_PASSWORD, host: OR_HOST, port: OR_PORT)
```

I think you don't have to do nearly as much escaping as you are on your query statement, either.  As-is, that will evaluate down to literally `"""SELECT UPPER(VALUE) AS VALUE FROM V$PARAMETER WHERE UPPER(NAME)='AUDIT_TRAIL';"""` - that is, a string beginning and ending with three double-quotes in a row.  That's probably not what you mean.  There is also an extra close paren hanging out in there.

If you mean this: `SELECT UPPER(VALUE) AS VALUE FROM V$PARAMETER WHERE UPPER(NAME)='AUDIT_TRAIL'` , all you have to say is 

```
describe sql.query("SELECT UPPER(VALUE) AS VALUE FROM V$PARAMETER WHERE UPPER(NAME)='AUDIT_TRAIL'").row(0).column('value') do
   its('value') { should eq 'DB, EXTENDED' }
 end
```
You don't have to escape anything; just use a quote that won't interfere with the single quotes.  Double quotes work fine.

I might suggest that you play around some in `inspec shell` or `irb` - those are both interactive environments where you can get a feel for this sort of thing.

Have a great day!
